// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'header': string;
  'myPicture': string;
  'pic': string;
  'text': string;
}
export const cssExports: CssExports;
export default cssExports;
