// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blueBlock': string;
  'home': string;
}
export const cssExports: CssExports;
export default cssExports;
